In [2]:
'''numpy is a python library, its stands for Numerical Python(numpy)
its consisting of multi-dimensionsal array objects'''

!pip install numpy
import numpy as np

In [13]:
a=np.array([2,5,88,45])
a

array([ 2,  5, 88, 45])

In [42]:
#dimensional-array like 2d,3d

a1=np.array(5)
a=np.array([2])
b=np.array([24,36,45])
c=np.array([[24,36,45],[55,88,66]])
d=np.array([[[24,36,45],[55,88,66],[29,39,49]]])
e=np.array([[[24,36,45],[55,88,66]],[[11,22,33],[77,89,99]]])

In [43]:
print('a1 dimension:',a1.ndim)
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)
print('e dimension:', e.ndim)

a1 dimension: 0
a dimension: 1
b dimension: 1
c dimension: 2
d dimension: 3
e dimension: 3


In [50]:
## find - shape of array

a1=np.array(5)
a=np.array([2])
b=np.array([24,36,45])
c=np.array([[24,36,45],[55,88,66]])
d=np.array([[[24,36,45],[55,88,66],[29,39,49]]])
e=np.array([[[24,36,45],[55,88,66]],[[11,22,33],[77,89,99]]])

print(a1)
print('a1 shape:',a1.shape)
print('----------')
print(a)
print('a shape:', a.shape)
print('----------')
print(b)
print('b shape:', b.shape)
print('-----------')
print(c)
print('c shape:', c.shape)
print('-----------')
print(d)
print('d shape:', d.shape)
print('-------------')
print(e)
print('e shape:', e.shape)

5
a1 shape: ()
----------
[2]
a shape: (1,)
----------
[24 36 45]
b shape: (3,)
-----------
[[24 36 45]
 [55 88 66]]
c shape: (2, 3)
-----------
[[[24 36 45]
  [55 88 66]
  [29 39 49]]]
d shape: (1, 3, 3)
-------------
[[[24 36 45]
  [55 88 66]]

 [[11 22 33]
  [77 89 99]]]
e shape: (2, 2, 3)


In [60]:
## data type

a1=np.array(5)
a=np.array([2])
b=np.array([24,36,45])
c=np.array([[24,36,45],[55,88,66]])
d=np.array([[[24,36,45],[55,88,66],[29,39,49]]])
e=np.array([[[24,36,45],[55,88,66]],[[11,22,33],[77,89,99]]])

print('a1 type:',a1.dtype)
print('a type:', a.dtype)
print('b type:', b.dtype)
print('c type:', c.dtype)
print('d type:', d.dtype)
print('e type:', e.dtype)

a1 type: int32
a type: int32
b type: int32
c type: int32
d type: int32
e type: int32


In [63]:
type(c)  # type func

numpy.ndarray

In [64]:
type(d)

numpy.ndarray

In [73]:
# length
len(b)

3

In [74]:
len(e)

2

In [78]:
np.arange(12,24) # range

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [79]:
np.arange(12,24,3)

array([12, 15, 18, 21])

In [89]:
np.eye(6,dtype=float) # eye function passing parameter

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [101]:
np.eye(5,7,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [104]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [105]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
np.full((4,6),4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [118]:
d=(24,25,26,27,28) ## diagonal function array
np.diag(d)

array([[24,  0,  0,  0,  0],
       [ 0, 25,  0,  0,  0],
       [ 0,  0, 26,  0,  0],
       [ 0,  0,  0, 27,  0],
       [ 0,  0,  0,  0, 28]])

In [143]:
import random   # random generate integer
np.random.random(3)[2]

0.3988726505824248

In [156]:
np.random.rand(4,3)

array([[0.14635282, 0.10153919, 0.25619568],
       [0.49906035, 0.9714526 , 0.44474371],
       [0.41101535, 0.19550629, 0.56378519],
       [0.53453225, 0.52147374, 0.0928892 ]])

In [163]:
r=np.arange(12,28)
r

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [164]:
r.shape

(16,)

In [167]:
r1=r.reshape(4,4) # covert 1x16 to 4x4
r1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [168]:
r1.shape  #  shape

(4, 4)

In [173]:
# convert old dimension
r2=r1.ravel()
r2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [175]:
r2.shape

(16,)

In [177]:
r

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [186]:
r.reshape(8,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [190]:
r.reshape(8,2,order='F')

array([[12, 20],
       [13, 21],
       [14, 22],
       [15, 23],
       [16, 24],
       [17, 25],
       [18, 26],
       [19, 27]])

In [193]:
r1.flatten()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [198]:
a=np.arange(3,22,3)
a

array([ 3,  6,  9, 12, 15, 18, 21])

In [206]:
a[3:22:2]

array([12, 18])

In [218]:
k=np.array([[[2,3,4],[5,6,7],[8,9,10],[45,2,8]]])
k.shape

(1, 4, 3)

In [220]:
k1=np.arange(15)
k1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [223]:
k2=k1
k2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [226]:
k2[5]=25
print(k2)
print(k1)

[ 0  1  2  3  4 25  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4 25  6  7  8  9 10 11 12 13 14]


In [234]:
print(np.shares_memory(k1,k2))
print(id(k1))
print(id(k2))

True
2351235265808
2351235265808


In [252]:
k3=k1.view()
np.shares_memory(k1,k3)

True

In [236]:
k3[4]=77
print(k1)
print(k3)

[ 0  1  2  3 77 25  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 77 25  6  7  8  9 10 11 12 13 14]


In [238]:
k4=np.copy(k1)
k4

array([ 0,  1,  2,  3, 77, 25,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [246]:
k4[-3]=0
print(k1)
print(k4)

[ 0  1  2  3 77 25  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 77 25  6  7  8  9 10 11  0 13 14]


In [250]:
np.shares_memory(k1,k4)


False

In [268]:
m=np.array([[24,25,26],[27,28,29],[30,31,38]])
m

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 38]])

In [269]:
m<28

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [270]:
m>28

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [275]:
m[m>28]

array([29, 30, 31, 38])

In [276]:
m[(m>28) & (m<34)]

array([29, 30, 31])

In [277]:
k1==k4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [278]:
k1==k3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [280]:
a

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 38]])

In [281]:
a.transpose()

array([[24, 27, 30],
       [25, 28, 31],
       [26, 29, 38]])

In [283]:
print(k1)
print(k4)
np.vstack((k1,k4))

[ 0  1  2  3 77 25  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 77 25  6  7  8  9 10 11  0 13 14]


array([[ 0,  1,  2,  3, 77, 25,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3, 77, 25,  6,  7,  8,  9, 10, 11,  0, 13, 14]])

In [284]:
np.hstack((k1,k4))

array([ 0,  1,  2,  3, 77, 25,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,
        2,  3, 77, 25,  6,  7,  8,  9, 10, 11,  0, 13, 14])

In [287]:
np.insert(k1,7,60)

array([ 0,  1,  2,  3, 77, 25,  6, 60,  7,  8,  9, 10, 11, 12, 13, 14])

In [288]:
np.insert(k1,7,k4)

array([ 0,  1,  2,  3, 77, 25,  6,  0,  1,  2,  3, 77, 25,  6,  7,  8,  9,
       10, 11,  0, 13, 14,  7,  8,  9, 10, 11, 12, 13, 14])

In [291]:
print(k1)        # index 5th 25 deleted
np.delete(k1,5)

[ 0  1  2  3 77 25  6  7  8  9 10 11 12 13 14]


array([ 0,  1,  2,  3, 77,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [292]:
a

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 38]])

In [294]:
np.sin(a)

array([[-0.90557836, -0.13235175,  0.76255845],
       [ 0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.29636858]])

In [296]:
np.tan(a)

array([[-2.1348967 , -0.13352641,  1.17875355],
       [-3.2737038 , -0.2814296 ,  0.88714284],
       [-6.4053312 , -0.44169557,  0.31030966]])

In [297]:
np.exp(a)

array([[2.64891221e+10, 7.20048993e+10, 1.95729609e+11],
       [5.32048241e+11, 1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 3.18559318e+16]])

In [298]:
np.sum(a)

258

In [300]:
np.sum(a,axis=0)

array([81, 84, 93])

In [299]:
np.sum(a,axis=1)

array([75, 84, 99])

In [301]:
a

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 38]])

In [302]:
np.mean(a)

28.666666666666668

In [305]:
np.median(a)

28.0

In [307]:
np.std(a)

3.9440531887330774

In [308]:
np.max(a)

38

In [310]:
k1

array([ 0,  1,  2,  3, 77, 25,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [309]:
np.sort(k1)

array([ 0,  1,  2,  3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 25, 77])

In [311]:
np.where(k1==10)

(array([10], dtype=int64),)

In [312]:
np.where(k1%5==0)

(array([ 0,  5, 10], dtype=int64),)

In [317]:
np.where(k1>7,k1,0)

array([ 0,  0,  0,  0, 77, 25,  0,  0,  8,  9, 10, 11, 12, 13, 14])