In [251]:
import numpy as np
import pandas as pd

In [252]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [253]:
b=np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [254]:
b.ndim

2

In [255]:
b.shape

(2, 4)

In [256]:
b.dtype

dtype('int32')

In [257]:
b.itemsize

4

In [258]:
a.nbytes

16

In [259]:
b.nbytes

32

In [260]:
b[0,1]

2

In [261]:
b[1,2]

3

In [262]:
b[0,:]                    # rows

array([1, 2, 3, 4])

In [263]:
b[:,2]                     # columns

array([3, 3])

In [264]:
s=np.full((4,3),8)
s

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [265]:
f=np.random.rand(4,4)
f

array([[0.68530633, 0.51786747, 0.04848454, 0.13786924],
       [0.18696743, 0.9943179 , 0.5206654 , 0.57878954],
       [0.73481906, 0.54196177, 0.91315356, 0.80792015],
       [0.40299783, 0.35722434, 0.95287671, 0.34363158]])

In [266]:
k=np.identity(6)
k

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [267]:
s+2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
           # pandas

In [268]:
!pip install pandas
import numpy as np
import pandas as pd

In [269]:
labels=['a','b','c']
data=[10,20,30]
arr=np.array(data)
d={'a':10,'b':20,'c':30}
labels
data


[10, 20, 30]

In [270]:
arr

array([10, 20, 30])

In [271]:
data

[10, 20, 30]

In [272]:
d

{'a': 10, 'b': 20, 'c': 30}

In [273]:
pd.Series(data=data)

0    10
1    20
2    30
dtype: int64

In [274]:
pd.Series(data=data,index=labels)

a    10
b    20
c    30
dtype: int64

In [275]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [276]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [277]:
ser1=pd.Series([11,22,33,44],['aa','bb','cc','dd'])
ser2=pd.Series([11,55,33,44],['aa','zz','cc','dd'])

In [278]:
ser1['aa']

11

In [279]:
ser2['aa']

11

In [280]:
ser2['zz']

55

In [281]:
ser1[2]

33

In [282]:
ser2[3]

44

In [283]:
ser2[2]

33

In [284]:
ser1[1:4]

bb    22
cc    33
dd    44
dtype: int64

In [285]:
ser2[2:3]

cc    33
dtype: int64

In [286]:
ser3=ser1+ser2

In [287]:
ser3

aa    22.0
bb     NaN
cc    66.0
dd    88.0
zz     NaN
dtype: float64

In [288]:
from numpy.random import rand as rn

In [289]:
np.random.seed(101)
data = rn(5,4)
row_labels=['A','B','C','D','E']
column_headings=['w','x','y','z']

df=pd.DataFrame(data=data,index=row_labels,columns=column_headings)

In [290]:
df

w         x         y         z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [291]:
df.x

A    0.570668
B    0.833897
C    0.189939
D    0.785602
E    0.603548
Name: x, dtype: float64

In [292]:
df['x']

A    0.570668
B    0.833897
C    0.189939
D    0.785602
E    0.603548
Name: x, dtype: float64

In [293]:
type(df.x)

pandas.core.series.Series

In [294]:
df[['x','z']]

x         z
A  0.570668  0.171522
B  0.833897  0.893613
C  0.189939  0.352132
D  0.785602  0.232354
E  0.603548  0.276239

In [295]:
df['x']+df['y']                               #adding columns

A    0.599142
B    1.140863
C    0.744167
D    1.751085
E    1.332541
dtype: float64

In [296]:
df.drop('A')                                          #deleting row

w         x         y         z
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [297]:
df1=df.drop('A')                                      #deleting row
df1

w         x         y         z
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [298]:
df.drop('C')

w         x         y         z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [299]:
# iloc are indexs and loc are rows #

In [300]:
df.loc['C']                              #loc are rows

w    0.721544
x    0.189939
y    0.554228
z    0.352132
Name: C, dtype: float64

In [301]:
df.loc[['B','C']]

w         x         y         z
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132

In [302]:
df.iloc[2]                         #iloc are indexs

w    0.721544
x    0.189939
y    0.554228
z    0.352132
Name: C, dtype: float64

In [303]:
df.iloc[[2,2]]

w         x         y         z
C  0.721544  0.189939  0.554228  0.352132
C  0.721544  0.189939  0.554228  0.352132

In [304]:
df.loc['B','y']              #subsetting dataframe

0.3069662196722378

In [305]:
df.loc[['B','C'],['y','x']]

y         x
B  0.306966  0.833897
C  0.554228  0.189939

In [306]:
df>0                              #conditional selection true or false

w     x     y     z
A  True  True  True  True
B  True  True  True  True
C  True  True  True  True
D  True  True  True  True
E  True  True  True  True

In [307]:
df.loc[['A','B','D']]>0

w     x     y     z
A  True  True  True  True
B  True  True  True  True
D  True  True  True  True

In [308]:
booldf=df>0
df[booldf]

w         x         y         z
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [309]:
                    #missing values

In [310]:
df=pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,5]})
df['rows']='xy yz zx' .split()
df.set_index('rows',inplace=True)
df



A    B  C
rows             
xy    1.0  5.0  1
yz    2.0  NaN  2
zx    NaN  NaN  5

In [311]:
 df.dropna(axis=0)           #axis=0 is rows , yz,zx deleted                                  #dropna method

A    B  C
rows             
xy    1.0  5.0  1

In [312]:
    df.dropna(axis=1)                          #axis=1 is columns, A, B deleted

C
rows   
xy    1
yz    2
zx    5

In [313]:
df.dropna(axis=0,thresh=2)                   #only zx deleted

A    B  C
rows             
xy    1.0  5.0  1
yz    2.0  NaN  2

In [314]:
df.fillna('santu')

A      B  C
rows                 
xy      1.0    5.0  1
yz      2.0  santu  2
zx    santu  santu  5

In [315]:
df.fillna(df['B'].mean())         #only B mean applied to all Nan

A    B  C
rows             
xy    1.0  5.0  1
yz    2.0  5.0  2
zx    5.0  5.0  5

In [316]:
  #group by method  

In [317]:
data={'company':['google','microsoft','apple','google','microsoft','apple'],
      'person':['rahul','rohit','kohli','phant','bumrah','shami'],
       'sales':[100,200,300,400,500,600]}
df=pd.DataFrame(data)
df

company  person  sales
0     google   rahul    100
1  microsoft   rohit    200
2      apple   kohli    300
3     google   phant    400
4  microsoft  bumrah    500
5      apple   shami    600

In [318]:
bycomp=df.groupby('company')        # use here (bycomp for df.group())
bycomp.mean()

sales
company         
apple        450
google       250
microsoft    350

In [319]:
bycomp.sum()

sales
company         
apple        900
google       500
microsoft    700

In [320]:
df.groupby('company').describe().loc[['apple','microsoft']]         #use here describe().loc()

sales                                                      
          count   mean         std    min    25%    50%    75%    max
company                                                              
apple       2.0  450.0  212.132034  300.0  375.0  450.0  525.0  600.0
microsoft   2.0  350.0  212.132034  200.0  275.0  350.0  425.0  500.0

In [321]:
df.groupby('company').describe().loc['apple']

sales  count      2.000000
       mean     450.000000
       std      212.132034
       min      300.000000
       25%      375.000000
       50%      450.000000
       75%      525.000000
       max      600.000000
Name: apple, dtype: float64

In [322]:
#   merging and  joining and concatenating

In [323]:
df1=pd.DataFrame({'P':['P1','P2','P3','P4'],
                  'Q':['Q1','Q2','Q3','Q4'],
                  'R':['R1','R2','R3','R4'],
                  'S':['S1','S2','S3','S4']})

df2=pd.DataFrame({'P':['P5','P6','P7','P8'],
                  'Q':['Q5','Q6','Q7','Q8'],
                  'R':['R5','R6','R7','R8'],
                  'S':['S5','S6','S7','S8']})                  
                                          

In [324]:
df1

P   Q   R   S
0  P1  Q1  R1  S1
1  P2  Q2  R2  S2
2  P3  Q3  R3  S3
3  P4  Q4  R4  S4

In [325]:
df2

P   Q   R   S
0  P5  Q5  R5  S5
1  P6  Q6  R6  S6
2  P7  Q7  R7  S7
3  P8  Q8  R8  S8

In [326]:
df_cat1=pd.concat([df1,df2],0)       # here use' 0 'or axis=0  
df_cat1

P   Q   R   S
0  P1  Q1  R1  S1
1  P2  Q2  R2  S2
2  P3  Q3  R3  S3
3  P4  Q4  R4  S4
0  P5  Q5  R5  S5
1  P6  Q6  R6  S6
2  P7  Q7  R7  S7
3  P8  Q8  R8  S8

In [327]:
df_cat2=pd.concat([df1,df2],1)        # here use' 1 'or axis=1
df_cat2

P   Q   R   S   P   Q   R   S
0  P1  Q1  R1  S1  P5  Q5  R5  S5
1  P2  Q2  R2  S2  P6  Q6  R6  S6
2  P3  Q3  R3  S3  P7  Q7  R7  S7
3  P4  Q4  R4  S4  P8  Q8  R8  S8

In [328]:
# merging by common '' key''

In [329]:
right=pd.DataFrame({'key':['k0','k2','k2','k3'],
                    'C':['c0','c1','c2','c3'],
                    'D':['d0','d1','d2','d3']}) 
right

key   C   D
0  k0  c0  d0
1  k2  c1  d1
2  k2  c2  d2
3  k3  c3  d3

In [330]:
left=pd.DataFrame({'key':['k0','k1','k2','k3'],
                    'A':['a0','a1','a2','a3'],
                    'B':['b0','b1','b2','b3']}) 
left


key   A   B
0  k0  a0  b0
1  k1  a1  b1
2  k2  a2  b2
3  k3  a3  b3

In [331]:
merge1=pd.merge(left,right)
merge1

key   A   B   C   D
0  k0  a0  b0  c0  d0
1  k2  a2  b2  c1  d1
2  k2  a2  b2  c2  d2
3  k3  a3  b3  c3  d3

In [332]:
right=pd.DataFrame({'key1':['k0','k1','k1','k2'],
                    'key2':['ko','ko','ko','ko'],
                    'C':['c0','c1','c2','c3'],
                    'D':['d0','d1','d2','d3']}) 
right

key1 key2   C   D
0   k0   ko  c0  d0
1   k1   ko  c1  d1
2   k1   ko  c2  d2
3   k2   ko  c3  d3

In [333]:
left=pd.DataFrame({'key1':['k0','k0','k1','k2'],
                   'key2':['ko','k1','ko','k1'],
                    'A':['a0','a1','a2','a3'],
                    'B':['b0','b1','b2','b3']}) 
left

key1 key2   A   B
0   k0   ko  a0  b0
1   k0   k1  a1  b1
2   k1   ko  a2  b2
3   k2   k1  a3  b3

In [334]:
pd.merge(left,right,how='outer',on=['key1','key2'])

key1 key2    A    B    C    D
0   k0   ko   a0   b0   c0   d0
1   k0   k1   a1   b1  NaN  NaN
2   k1   ko   a2   b2   c1   d1
3   k1   ko   a2   b2   c2   d2
4   k2   k1   a3   b3  NaN  NaN
5   k2   ko  NaN  NaN   c3   d3

In [335]:
pd.merge(left,right,how='inner',on=['key1','key2'])

key1 key2   A   B   C   D
0   k0   ko  a0  b0  c0  d0
1   k1   ko  a2  b2  c1  d1
2   k1   ko  a2  b2  c2  d2

In [336]:
left.join('right,how='outer')

SyntaxError: invalid syntax (<ipython-input-336-9a6455ae1e3a>, line 1)

In [ ]:
       # apply methods

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({'col1':[1,2,3,4,5,6,7,8,9],
                 'col2':[11,22,33,44,22,33,44,55,66],
                 'col3':['a','bb','c','ddd','e','fff','g','h','ii']})
df

In [338]:
df.head()

company  person  sales
0     google   rahul    100
1  microsoft   rohit    200
2      apple   kohli    300
3     google   phant    400
4  microsoft  bumrah    500

In [ ]:
df.tail()

In [ ]:
df.col2.unique()

In [ ]:
df.col2.nunique()

In [ ]:
df.col2.value_counts()

In [ ]:
   #apply methods